### PR TITLE
_cleantarget_ feature addition

### PR DESCRIPTION
**Pull request by iamOgunyinka**

### CODE REVIEW

**Comment by codingo** [comment]
Not ignoring this, just no time to properly test as yet. Aiming to review Monday.

**Comment by CharlieEriksen** [comment]
Can't wait for this to land! <3

**Comment by codingo** [comment]
Makes sense, I'm on holidays until Friday but @prodigysml may be able to get to this before then.

**Comment by codingo** [comment]
Sorry for not landing this yet - BSides Perth presentation drowned me. Looking soon.

**Pull request merged**
