### PR TITLE
Add option to repeat the command

### LINKED ISSUE #80: -repeat and _repeat_ option to repeat a queue
A few use case require running a command more than once. Currently, Interlace de-duplicates queues, which removes the ability to workaround this by issuing a command more than once.

This has led to two suggested changes to improve Interlace's utility:

# -repeat x
This command when passed on the command line would simply repeat the entire command queue (-c or -cL) x number of times.

# _repeat:x_
This command when used in a command file would repeat whatever was in the block (starting/ending with `_repeat:x_`) x number of times.

### PR DESCRIPTION
**Pull request by mzfr**
Fixes #80 

I have made the changes according to what I understood the option `--repeat` should do. If you think this is not the right way then please let me know I'd be happy to make the changes.

### CODE REVIEW

**Comment by codingo** [comment]
Reviewing this Monday, very sorry for the delay!

**Comment by mzfr** [comment]
@codingo Any updates on this one?

**Comment by mzfr** [comment]
@codingo any updates on this?

**Comment by codingo** [comment]
Hi @mzfr, sorry about the delay - if you can send me your twitter handle on here I'll send your pentesterlab sub now, and then aim to merge this tomorrow.

**Comment by mzfr** [comment]
Oh okay.

My twitter handle is: 0xmzfr

**Comment by codingo** [comment]
Sent!

**Pull request merged**
