### PR TITLE
Update input.py

### PR DESCRIPTION
**Pull request by alanEG**
#140

### CODE REVIEW

**Comment by prodigysml** [comment]
Whoops! Clearly we either forgot to implement the feature or removed it somewhere! Thanks for fixing this @alanEG!

**Review by prodigysml — APPROVED** [review]

**Comment by prodigysml** [comment]
Still needs a version increment. I'll add that in a bit. Feel free to add in a commit for incrementing the minor version if you can before @alanEG

**Comment by alanEG** [comment]
excuse me i don't know what is commit for incrementing
So I'll leave it to you

**Comment by prodigysml** [comment]
Couldn't write to your fork, so I just did another push to increment the version. Thanks so much for your help!

**Pull request merged**
