### PR TITLE
Improve memory usage in the generation of tasks (to fix issue #119)

### PR DESCRIPTION
**Pull request by whiteroses**
Switch to generating tasks using iterators, and make other changes such
as using netaddr's IPSet to store ranges of IP addresses, in order to
reduce the use of memory where possible.

### CODE REVIEW

**Comment by prodigysml** [comment]
Testing this PR out now. So far using the following:
```
prips 0.0.0.0/16 > x
time interlace -tL x -c "echo _target_"
```

Maxes out CPU (as expected) and has RAM at 0.8% (of an 8GB machine), which is approximately 80MB RAM usage. Looking great so far!

**Comment by prodigysml** [comment]
Output:
```
100%|████████████████████████████████████| 65536/65536 [04:05<00:00, 266.79it/s]

real    87m54.558s
user    84m47.646s
sys     5m25.266s
```

**Comment by prodigysml** [comment]
Thats a real good PR @whiteroses! Fixes the issue for sure! Please ping me on twitter (https://twitter.com/sml555_) and I'll arrange the bounty payout! Also, any chance you would be interested in implementing multi-threading for the command creation? :)

**Comment by whiteroses** [comment]
@prodigysml: Glad it resolves the issue! :) (Will DM you on Twitter.) Which part of command creation are you looking to speed up with multi-threading? (Is [this output](https://github.com/codingo/Interlace/pull/121#issuecomment-703101489) from [this command](https://github.com/codingo/Interlace/pull/121#issuecomment-703078167)?)

**Comment by prodigysml** [comment]
Yes, the output is from that command. I believe the replacement process is the slowest part atm. It's been something we wanted to fix for a bit, but haven't been able to get to yet. Basically using the same number of threads as provided in the args, to create the commands and do the variable replacement.

**Comment by whiteroses** [comment]
I'm wondering why there is such a huge difference between your output and mine -- trying your command on my (several years old, not powerful) machine, this is the kind of output I get, even with other applications running:

<pre>
65536/65536 [02:30<00:00, 436.35it/s]

real	2m36.983s
user	2m26.985s
sys	2m22.518s
</pre>

Are you getting the same 80+m "real" elapsed time on every run?

If I'm understanding correctly, the replacement process is (aside from reading targets and exclusions from files) all CPU-bound, and threads would not help (and might even slow things down) given the Global Interpreter Lock in CPython?

**Pull request merged**
